### ISSUE TITLE
Swift style guide: trailing closure when more than one closure param present

### ISSUE THREAD

**Issue by KiGi** [SlideShareInc/swift-style-guide#1]
In the Swift guide is says:

_However, if there are 2 closures as the last parameters, do not use trailing closure syntax for the last one as this is ambiguous._

I thought as of Swift 1.2 it was non-ambiguous, and would always use the last one?  Or do you mean it's ambiguous to a developer reading the code?

**Comment by drumnkyle** [comment]
This is not an issue of compilation. It is, as you alluded to, an issue of ambiguity for the developer. We feel it is better to use trailing closure syntax only when you have a single trailing closure. This happens mostly when there is a completion block as the last parameter or something of the sort.

**Comment by drumnkyle** [comment]
I will close this issue. If you have any other concerns I can reopen it or you can make a new issue.
